### ISSUE TITLE
Idea: Filter tasks by category, priority, due date

### ISSUE THREAD

**Issue by krnekhelesh** [sonrisesoftware/tasks-app#2] opened 2013-08-13 08:01 UTC
In the home view, currently tasks can be seen in the order they are created. It would be nice if this view can filtered according to certain criteria such as their category, priority or due date.

For instance if the user filters them by category, then using a listview it should show something similar to,
- Category Header 1
  - Task 1
  - Task 2
- Category Header 2
  - Task 5
- Category Header 3
  - Task 6

**Comment by iBelieve** [comment] 2013-08-17 13:29
I'm closing this as a duplicate of #11, since that has a more relevant design with the new convergent layout.

**Closed as completed by iBelieve** 2013-08-17 13:29 UTC
Labels: duplicate, enhancement

**Comment by iBelieve** [comment] 2013-08-17 13:32
Though I will have a similar feature for individual task lists where the user can sort by different criteria (see #12).
